name: last-build
description: ''
inputs:
  arch:
    description: ''
    required: false
    default: ''
    type: string
  tools:
    description: ''
    required: false
    default: ''
    type: string
  owdebug:
    description: ''
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
###########################################
# load all parts(artifacts) of distribution
###########################################
  - uses: "./.github/actions/artfload"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'rel'
      artifact: 'rel nt'
  - uses: "./.github/actions/artfload"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'rel'
      artifact: 'rel lnx'
      tools:    'gcc'
  - uses: "./.github/actions/artfload"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'rel'
      artifact: 'rel docsall'
###########################################
# create CI snapshot artifact, upload it
###########################################
  - id: tarname
    run: >
      Join-Path ${{ runner.temp }} ow-snapshot.tar.xz
      | Join-String -OutputPrefix 'fullname='
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - uses: "./.github/actions/tarsave"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'rel'
      fullname: ${{ steps.tarname.outputs.fullname }}
  - id: snapshot
    run: >
      Join-Path ${{ github.workspace }} ow-snapshot.tar.xz
      | Join-String -OutputPrefix 'path='
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - run: |
      Move-Item -Path ${{ steps.tarname.outputs.fullname }} -Destination ${{ steps.snapshot.outputs.path }}
    shell: pwsh
  - name: Upload Artifact owsnapshot
    uses: actions/upload-artifact@v3
    with:
      name: owsnapshot
      path: ${{ steps.snapshot.outputs.path }}
      retention-days: 2
###########################################
# create CI release, overwrite existin one
###########################################
  - if: github.event_name != 'PullRequest'
    id: cireldata
    run: |
      echo "tag=Last-CI-build" >> ${{ github.output }}
      echo "timestamp=$(date +'%Y-%m-%d %H:%M:%S')" >> ${{ github.output }}
    shell: bash
  - if: github.event_name != 'PullRequest'
    uses: "./.github/actions/ghreldel"
    with:
      tag:     ${{ steps.cireldata.outputs.tag }}
      owdebug: ${{ inputs.owdebug }}
  - if: github.event_name != 'PullRequest'
    id: newcirel
    uses: "./.github/actions/ghrelcre"
    with:
      note:    Last updated ${{ steps.cireldata.outputs.timestamp }}
      title:   ${{ steps.cireldata.outputs.tag }}
      tag:     ${{ steps.cireldata.outputs.tag }}
      tagmsg:  ${{ steps.cireldata.outputs.timestamp }}
      owdebug: ${{ inputs.owdebug }}
  - if: steps.newcirel.outputs.id != ''
    run: |
      echo "${{ steps.newcirel.outputs.id }}"
      $fname = Join-Path ${{ github.workspace }} ow-snapshot.tar.xz
      $response = curl -s -L -X POST `
      "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.newcirel.outputs.id }}/assets?name=ow-snapshot.tar.xz" `
      -H "Accept: application/vnd.github+json" `
      -H "Authorization: Bearer ${{ github.token }}" `
      -H "X-GitHub-Api-Version: 2022-11-28" `
      -H "Content-Type: application/octet-stream" `
      --data-binary "@$fname"
      if( "${{ inputs.owdebug }}" -eq '1' ) { $response }
    shell: pwsh
