name: documentation-build
description: ''
inputs:
  target:
    description: ''
    required: false
    default: ''
    type: string
  arch:
    description: ''
    required: false
    default: ''
    type: string
  tools:
    description: ''
    required: false
    default: ''
    type: string
  owtools:
    description: ''
    required: false
    default: ''
    type: string
  owdebug:
    description: ''
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - uses: "./.github/actions/dosboxin"
    with:
      arch:     ${{ inputs.arch }}
  - uses: "./.github/actions/artfload"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'build binbuild'
      artifact: "build ${{ inputs.arch }}"
      tools:    ${{ inputs.tools }}
  - name: Documentation Build
    run: ci/buildx.cmd ${{ inputs.tools }}
    env:
      OWBUILD_STAGE: 'docs'
      OWDOCTARGET:   ${{ inputs.target }}
      OWTOOLS:       ${{ inputs.owtools }}
      OWROOT:        ${{ github.workspace }}
      OWDOSBOX:      'dosbox.exe'
      OWDOSBOXPATH:  ${{ github.workspace }}\ci\nt386
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: cmd
  - uses: "./.github/actions/artfsave"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'rel'
      artifact: "rel ${{ inputs.target }}"
      tools:    ${{ inputs.tools }}
