name: last-build
description: ''
inputs:
  tag:
    description: ''
    required: false
    default: ''
    type: string
  owdebug:
    description: ''
    required: false
    default: ''
    type: string
outputs:
  sha:
    description: ''
    value: ${{ steps.tagref.outputs.sha }}
  old:
    description: ''
    value: ${{ steps.tagref.outputs.old }}
runs:
  using: composite
  steps:
  - id: tagref
    run: |
      $response = curl -s -L `
      -H "Accept: application/vnd.github+json" `
      -H "Authorization: Bearer ${{ github.token }}" `
      -H "X-GitHub-Api-Version: 2022-11-28" `
      "https://api.github.com/repos/${{ github.repository }}/git/ref/tags/${{ inputs.tag }}"
      if( "${{ inputs.owdebug }}" -eq '1' ) { $response }
      if( "${{ inputs.owdebug }}" -eq '1' ) { $response | jq -r .object.sha }
      $sha = $response | jq -r .object.sha
      if( "$sha" -eq 'null' ) { $sha = '' }
      if( "$sha" -ne '' ) {
        $type = $response | jq -r .object.type
        if( "$type" -eq 'tag' ) {
          $response = curl -s -L `
          -H "Accept: application/vnd.github+json" `
          -H "Authorization: Bearer ${{ github.token }}" `
          -H "X-GitHub-Api-Version: 2022-11-28" `
          "https://api.github.com/repos/${{ github.repository }}/git/tags/$sha"
          $response
          $sha = $response | jq -r .object.sha
        } elseif( "$type" -eq 'commit' ) {
        } else {
          $sha = ''
        }
      }
      if( "${{ inputs.owdebug }}" -eq '1' ) { "sha=$sha" }
      $sha | Join-String -OutputPrefix 'sha=' | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
      if( "$sha" -ne "${{ github.sha }}" ) {
        'old=1' | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
        if( "${{ inputs.owdebug }}" -eq '1' ) { 'old=1' }
      }
    shell: pwsh
