name: artifact-load
inputs:
  arch:
    required: false
    default: ''
    type: string
  gitpath:
    required: false
    default: ''
    type: string
  artifact:
    required: false
    default: ''
    type: string
  tools:
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - name: Get Artifact name
    id: artifact-name
    run: >
      -Split "${{ inputs.artifact }} ${{ inputs.tools }}"
      | Join-String -Separator '-' -OutputPrefix 'id='
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - name: Download Artifact ${{ steps.artifact-name.outputs.id }}
    uses: actions/download-artifact@v3
    with:
      name: ${{ steps.artifact-name.outputs.id }}
      path: ${{ runner.temp }}
  - name: Get tar file name
    id: tarname
    run: >
      Join-Path ${{ runner.temp }} owartifact.tar.xz
      | Join-String -OutputPrefix 'fullname='
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - name: Restore Artifact
    uses: "./.github/actions/tarload"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  ${{ inputs.gitpath }}
      fullname: ${{ steps.tarname.outputs.fullname }}
  - name: Delete Temporary Artifact tar file
    run: rm -f ${{ steps.tarname.outputs.fullname }}
    shell: bash
