name: do-release
description: ''
inputs:
  tag:
    description: 'tag used for release'
    required: false
    default: ''
    type: string
  owdebug:
    description: ''
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - id: ghrel
    run: |
      $response = curl -s -L `
      "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ inputs.tag }}" `
      -H "Accept: application/vnd.github+json" `
      -H "Authorization: Bearer ${{ github.token }}" `
      -H "X-GitHub-Api-Version: 2022-11-28"
      if( "${{ inputs.owdebug }}" -eq '1' ) { $response }
      $id = $response | jq -r .id
      if( "$id" -eq 'null' ) { $id = '' }
      $id | Join-String -OutputPrefix 'id=' | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - if: steps.ghrel.outputs.id != ''
    name: "Remove Release Assets"
    run: |
      echo "${{ steps.ghrel.outputs.id }}"
      $response = curl -s -L `
      "https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.ghrel.outputs.id }}/assets" `
      -H "Accept: application/vnd.github+json" `
      -H "Authorization: Bearer ${{ github.token }}" `
      -H "X-GitHub-Api-Version: 2022-11-28"
      if( "${{ inputs.owdebug }}" -eq '1' ) { $response }
      $id = $response | jq -r .[].id
      if( "$id" -eq 'null' ) { $id = '' }
      $id | Foreach-Object {
        $response = curl -s -L -X DELETE `
        "https://api.github.com/repos/${{ github.repository }}/releases/assets/$_" `
        -H "Accept: application/vnd.github+json" `
        -H "Authorization: Bearer ${{ github.token }}" `
        -H "X-GitHub-Api-Version: 2022-11-28"
        if( "${{ inputs.owdebug }}" -eq '1' ) { $response }
      }
    shell: pwsh
  - if: steps.ghrel.outputs.id != ''
    name: "Remove Release"
    run: |
      $response = curl -s -L -X DELETE `
      "https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.ghrel.outputs.id }}" `
      -H "Accept: application/vnd.github+json" `
      -H "Authorization: Bearer ${{ github.token }}" `
      -H "X-GitHub-Api-Version: 2022-11-28"
      if( "${{ inputs.owdebug }}" -eq '1' ) { $response }
    shell: pwsh
  - name: "Remove Release Tag"
    run: |
      $response = curl -s -L -X DELETE `
      "https://api.github.com/repos/${{ github.repository }}/git/refs/tags/${{ inputs.tag }}" `
      -H "Accept: application/vnd.github+json" `
      -H "Authorization: Bearer ${{ github.token }}" `
      -H "X-GitHub-Api-Version: 2022-11-28"
      if( "${{ inputs.owdebug }}" -eq '1' ) { $response }
    shell: pwsh
