name: artifact-save
description: ''
inputs:
  arch:
    description: ''
    required: false
    default: ''
    type: string
  gitpath:
    description: ''
    required: false
    default: ''
    type: string
  artifact:
    description: ''
    required: false
    default: ''
    type: string
  tools:
    description: ''
    required: false
    default: ''
    type: string
  retention-days:
    description: ''
    required: false
    default: 3
    type: string
  verbose:
    description: ''
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - id: tarname
    run: >
      Join-Path ${{ runner.temp }} owartifact.tar.xz
      | Join-String -OutputPrefix 'fullname='
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - uses: "./.github/actions/tarsave"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  ${{ inputs.gitpath }}
      fullname: ${{ steps.tarname.outputs.fullname }}
      verbose:  ${{ inputs.verbose }}
  - name: Get Artifact name
    id: artifact-name
    run: >
      -Split "${{ inputs.artifact }} ${{ inputs.tools }}"
      | Join-String -Separator '-' -OutputPrefix 'id='
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - name: Upload Artifact ${{ steps.artifact-name.outputs.id }}
    uses: actions/upload-artifact@v3
    with:
      name:             ${{ steps.artifact-name.outputs.id }}
      path:             ${{ steps.tarname.outputs.fullname }}
      retention-days:   ${{ inputs.retention-days }}
  - name: Delete Temporary Artifact tar file
    run: rm -f ${{ steps.tarname.outputs.fullname }}
    shell: bash
