name: install
description: ''
inputs:
  arch:
    required: false
    default: ''
    type: string
  pscript:
    required: false
    default: ''
    type: string
  tools:
    required: false
    default: ''
    type: string
  owdebug:
    description: ''
    required: false
    default: ''
    type: string
runs:
  using: composite
  steps:
  - uses: "./.github/actions/artfload"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'build binbuild'
      artifact: build ${{ inputs.arch }}
      tools:    ${{ inputs.tools }}
  - uses: "./.github/actions/artfload"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'bld setupgui'
      artifact: 'bld setupgui nt'
  - uses: "./.github/actions/artfload"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'bld setupgui'
      artifact: 'bld setupgui lnx'
      tools:    'gcc'
  # consolidate binaries
  - uses: "./.github/actions/artfload"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'rel'
      artifact: 'rel nt'
  - uses: "./.github/actions/artfload"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'rel'
      artifact: 'rel lnx'
      tools:    'gcc'
  # consolidated documentation
  - uses: "./.github/actions/artfload"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'rel'
      artifact: 'rel docsall'
  # run build script
  - if: inputs.arch == 'lnx'
    name: Build Installers
    run: ${{ inputs.pscript }}
    env:
      OWBUILD_STAGE: 'inst'
      OWTOOLS:       'GCC'
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: bash
  - if: inputs.arch == 'osx'
    name: Build Installers
    run: ${{ inputs.pscript }}
    env:
      OWBUILD_STAGE: 'inst'
      OWTOOLS:       'CLANG'
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: bash
  - if: inputs.arch == 'nt'
    name: Build Installers
    run: ${{ inputs.pscript }}
    env:
      OWBUILD_STAGE: 'inst'
      OWTOOLS:       'VISUALC'
      OWIMAGE:       'windows-2019'
      OWROOT:        ${{ github.workspace }}
      OWDEBUG:       ${{ inputs.owdebug }}
      OWVERBOSE:     1
    shell: cmd
  # create full binary snapshot archive
  - id: tarname
    run: >
      Join-Path ${{ github.workspace }} distrib ow bin ow-snapshot.tar.xz
      | Join-String -OutputPrefix 'path='
      | Out-File -FilePath ${{ github.output }} -Encoding utf8 -Append
    shell: pwsh
  - uses: "./.github/actions/tarsave"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'rel'
      tarname:  ${{ steps.tarname.outputs.path }}
  # save all artifacts for distribution
  # full content of directory, cannot specify files
  - uses: "./.github/actions/artfsave"
    with:
      arch:     ${{ inputs.arch }}
      gitpath:  'distrib ow bin'
      artifact: 'distrib bin'
