parameters:
  arch:     ''
  title:    ''
  image:    ''
  pscript:  ''
  artifsuf: ''

jobs:
  - job: boot${{ parameters.arch }}
    displayName: "${{ parameters.title }}"
    pool:
      vmImage: ${{ parameters.image }}
    steps:
    - script: ${{ parameters.pscript }}
      displayName:  "Bootstrap"
    - template: artfsave.yml
      parameters:
        path:       build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}${{ parameters.artifsuf }}
    - template: artfsave.yml
      parameters:
        path:       bld/watcom/$(owobjdir)
        artifname:  bld-watcom-${{ parameters.arch }}${{ parameters.artifsuf }}
