parameters:
  arch:     ''
  title:    ''
  image:    ''
  pscript:  ''
  artifsuf: ''

jobs:
  - job: build${{ parameters.arch }}
    displayName: "${{ parameters.title }}"
    pool:
      vmImage: ${{ parameters.image }}
    timeoutInMinutes: 120
    steps:
    - template: dosbox.yml
      parameters:
        arch: ${{ parameters.arch }}
    - template: artfload.yml
      parameters:
        path:       build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}${{ parameters.artifsuf }}
    - template: artfload.yml
      parameters:
        path:       bld/watcom/$(owobjdir)
        artifname:  bld-watcom-${{ parameters.arch }}${{ parameters.artifsuf }}
    - script: ${{ parameters.pscript }}
      displayName: "Build"
    - ${{ if in(parameters.arch, 'lnx', 'nt') }}:
      - template: artfsave.yml
        parameters:
          path:         rel
          artifname:    rel-${{ parameters.arch }}${{ parameters.artifsuf }}
      - template: artfsave.yml
        parameters:
          path:         bld/setupgui
          artifname:    bld-setupgui-${{ parameters.arch }}${{ parameters.artifsuf }}
