parameters:
  arch:     ''
  title:    ''
  image:    ''
  pscript:  ''

jobs:
  - job: instal${{ parameters.arch }}
    displayName: "${{ parameters.title }}"
    pool:
      vmImage: ${{ parameters.image }}
    steps:
    - template: artfload.yml
      parameters:
        path:       build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}
    - template: artfload.yml
      parameters:
        path:       bld/setupgui
        artifname:  bld-setupgui-nt
    - template: artfload.yml
      parameters:
        path:       bld/setupgui
        artifname:  bld-setupgui-lnx
    # consolidate binaries
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-nt
    - template: artfload.yml
      parameters:
        path:       rel
        artifname:  rel-lnx
    # consolidate documentation
    - template: docsload.yml
    # run build script
    - script: ${{ parameters.pscript }}
      displayName: "Build Installers"
    # create full binary snapshot archive
    - ${{ if eq(parameters.arch, 'lnx') }}:
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(owroot)/rel'
          includeRootFolder: false
          archiveType: 'tar'
          tarCompression: 'xz'
          archiveFile: '$(owroot)/distrib/ow/bin/$(owsnapshotfile)'
          replaceExistingArchive: true
    # save all artifacts for distribution
    # full content of directory, cannot specify files
    - template: artfsave.yml
      parameters:
        path:       distrib/ow/bin
        artifname:  distrib-bin
