parameters:
  arch:     ''
  title:    ''
  image:    ''

jobs:
  - job: release
    displayName: "${{ parameters.title }}"
    variables:
      owtag:            Current-build
      owsubtag:         Build
    pool:
      vmImage:  ${{ parameters.image }}
    steps:
    - template: gituser.yml
    - checkout: self
      persistCredentials: true
    - template: artfload.yml
      parameters:
        path:       build/$(owobjdir)
        artifname:  build-${{ parameters.arch }}
    # DOS installers
    - template: artfload.yml
      parameters:
        path:       distrib/ow/bin
        artifname:  distrib-dos
    # OS/2 installers
    - template: artfload.yml
      parameters:
        path:       distrib/ow/bin
        artifname:  distrib-os2
    # WIN16 installers
    - template: artfload.yml
      parameters:
        path:       distrib/ow/bin
        artifname:  distrib-win16
    # WINNT installers
    - template: artfload.yml
      parameters:
        path:       distrib/ow/bin
        artifname:  distrib-nt
    # Linux installers
    - template: artfload.yml
      parameters:
        path:       distrib/ow/bin
        artifname:  distrib-lnx
    - bash: echo "##vso[task.setvariable variable=owtagstamp;]`date +'%Y-%m-%d %H:%M:%S'`"
      displayName: "Get current timestamp"
    - bash: echo "##vso[task.setvariable variable=owgitstamp;]`git ls-remote --tags . | sed -n -e \"s:\([0-9a-z]*\) *refs/tags/${{ variables.owtag }}^{}:\1:p\"`"
      displayName: "Get 'Current-build' tag commit"
    - script: |
        if [ ! "$OWGITSTAMP" = "$BUILD_SOURCEVERSION" ]; then
          git tag -d $OWTAG
          git push --delete origin $OWTAG
          git tag -a -m "$OWTAGSTAMP" $OWTAG $BUILD_SOURCEVERSION
          git push $(owgitverbose) origin $OWTAG
        else
          echo "##vso[task.setvariable variable=owtagstamp;]`git tag -l --format='%(contents)' $OWTAG`"
        fi
      displayName: "Recreate 'Current-build' tag"
    - template: doreleas.yml
      parameters:
        arch:      ${{ parameters.arch }}
        update:    'true'
        fullset:   'true'
        disp:      'Update daily Release'
        title:     '$(owtag)'
        tag:       '$(owtag)'
        timestamp: '$(owtagstamp)'
    - bash: echo "##vso[task.setvariable variable=owmtagmonth;]`date +'%Y-%m-'`"
      displayName: "Get current month stamp"
    - bash: echo "##vso[task.setvariable variable=owreleasecommit;]`git ls-remote --tags . | sed -n -e \"s:\([0-9a-z]*\) *refs/tags/$OWMTAGMONTH.*$(owsubtag)$:\1:p\"`"
      displayName: "Get current month build tag commit"
    - bash: echo "##vso[task.setvariable variable=owmtagstamp;]`date +'%Y-%m-%d'`"
      displayName: "Get current date"
    - bash: echo "##vso[task.setvariable variable=owmtag;]$(owmtagstamp)-$(owsubtag)"
      displayName: "Get current tag"
    - script: |
        if [ -z "$OWRELEASECOMMIT" ]; then
          git tag -a -m "$OWMTAGSTAMP $OWSUBTAG" $OWMTAG $BUILD_SOURCEVERSION
          git push $(owgitverbose) origin $OWMTAG
        fi
      displayName: "Create new permanent build tag"
    - template: doreleas.yml
      parameters:
        arch:      ${{ parameters.arch }}
        update:    'false'
        fullset:   'true'
        disp:      'Add monthly Release'
        title:     '$(owmtagstamp) $(owsubtag)'
        tag:       '$(owmtag)'
        timestamp: '$(owtagstamp)'
