name: Coverity-Scan
run-name: Coverity Scan tools download, build and send data to analysis
on:
  schedule:
    - cron:  '0 1 * * *'
env:
  OWCOVERITY_PROJECT: open-watcom/open-watcom-v2
  OWCOVERITY_TOOL_BASE: coverity-scan-analysis
jobs:
  check-run:
    name: Start
    runs-on: ubuntu-latest
    outputs:
      runit: ${{ steps.check-tag.outputs.old }}
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Check tag reference
      id: check-tag
      uses: "./.github/actions/ghtagchk"
      with:
        tag:     Coverity-scan
        ghtoken: ${{ secrets.GITHUB_TOKEN }}
        owdebug: 1
  scan-lnx:
    needs: check-run
    if: needs.check-run.outputs.runit && github.repository == 'open-watcom/open-watcom-v2'
    name: "Coverity Scan Linux"
    runs-on: ubuntu-latest
    #timeoutInMinutes: 90
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/coverity"
      with:
        arch:    'lnx'
        #title:   'Coverity Scan Linux'
        cscript: 'ci/covbuild.sh'
        pscript: 'ci/coverity.sh'
        tool_src: linux64
        tool_base: coverity-scan-analysis
        tool_archive: cov-analysis-linux.tgz
        result_archive: open-watcom-v2.tgz
        coverity_token: ${{ secrets.OWCOVERITY_TOKEN }}
        owdebug: ${{ vars.OWDEBUG }}
      env:
        OWTOOLS: GCC
        OWDOSBOX: dosbox
      
#  scan-nt:
#    needs: check-run
#    if: needs.check-run.outputs.runit && github.repository == 'open-watcom/open-watcom-v2'
#    name: "Coverity Scan Windows"
#    runs-on: windows-2022
#    timeoutInMinutes: 90
#    - name: checkout
#      uses: actions/checkout@v3.5.0
#    - uses: "./.github/actions/coverity"
#      with:
#        arch:    'nt'
#        #title:   'Coverity Scan Windows'
#        cscript: 'ci\covbuild.cmd'
#        pscript: 'ci\coverity.cmd'
#        tool_src: win64
#        tool_base: coverity-scan-analysis
#        tool_archive: cov-analysis-linux.zip
#        result_archive: open-watcom-v2.zip
#        coverity_token: ${{ secrets.OWCOVERITY_TOKEN }}
#        owdebug: ${{ vars.OWDEBUG }}
#      env:
#        OWTOOLS: VISUALC
#        OWIMAGE: windows-2022
#        OWDOSBOX: dosbox.exe
#        OWDOSBOXPATH: ci\nt386
