name: Release-Build
run-name: Release build (daily and monthly)
on:
  schedule:
    - cron:  '30 0 * * *'
jobs:
  check-run:
    name: Start
    runs-on: ubuntu-20.04
    outputs:
      runit: ${{ steps.check-tag.outputs.old }}
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Check tag reference
      id: check-tag
      uses: "./.github/actions/ghtagchk"
      with:
        tag:     Current-build
        owdebug: ${{ vars.OWDEBUG }}
  boot-lnx-gcc:
    needs: check-run
    if: needs.check-run.outputs.runit && github.repository == 'open-watcom/open-watcom-v2'
    name: Bootstrap Linux GCC
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Bootstrap Linux
      uses: "./.github/actions/boot"
      with:
        arch:    'lnx'
        pscript: 'ci/buildx.sh'
        tools:   'gcc'
        owtools: 'GCC'
        owdebug: ${{ vars.OWDEBUG }}
  boot-nt:
    needs: check-run
    if: needs.check-run.outputs.runit && github.repository == 'open-watcom/open-watcom-v2'
    name: Bootstrap Windows
    runs-on: windows-2019
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Bootstrap Windows
      uses: "./.github/actions/boot"
      with:
        arch:    'nt'
        pscript: 'ci/buildx.cmd'
        tools:   'vs2019'
        owtools: 'VISUALC'
        owdebug: ${{ vars.OWDEBUG }}
#  boot-osx:
#    needs: check-run
#    if: needs.check-run.outputs.runit && github.repository == 'open-watcom/open-watcom-v2'
#    name: Bootstrap OSX
#    runs-on: macos-11
#    steps:
#    - name: checkout
#      uses: actions/checkout@v3.5.0
#    - name: Bootstrap OSX
#      uses: "./.github/actions/boot"
#      with:
#        arch:    'osx'
#        pscript: 'ci/buildx.sh'
#        tools:   'clang'
#        owtools: 'CLANG'
#        owdebug: ${{ vars.OWDEBUG }}
  build-lnx-gcc:
    name: Build Linux GCC
    needs: boot-lnx-gcc
    runs-on: ubuntu-20.04
    timeout-minutes: 120
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Build Linux GCC
      uses: "./.github/actions/build"
      with:
        arch:    'lnx'
        pscript: 'ci/buildx.sh'
        tools:   'gcc'
        owtools: 'GCC'
        owdebug: ${{ vars.OWDEBUG }}
  build-nt:
    name: Build Windows
    needs: boot-nt
    runs-on: windows-2019
    timeout-minutes: 120
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Build Windows
      uses: "./.github/actions/build"
      with:
        arch:    'nt'
        pscript: 'ci/buildx.cmd'
        tools:   'vs2019'
        owtools: 'VISUALC'
        owdebug: ${{ vars.OWDEBUG }}
#  build-osx:
#    name: Build OSX
#    needs: boot-osx
#    runs-on: macos-11
#    timeout-minutes: 120
#    steps:
#    - name: checkout
#      uses: actions/checkout@v3.5.0
#    - name: Build OSX
#      uses: "./.github/actions/build"
#      with:
#        arch:    'osx'
#        pscript: 'ci/buildx.sh'
#        tools:   'clang'
#        owtools: 'CLANG'
#        owdebug: ${{ vars.OWDEBUG }}
  docsbuild-dos:
    name: Documentation Build DOS
    needs: boot-nt
    runs-on: windows-2019
    timeout-minutes: 90
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/docbuild"
      with:
        target:     'docdos'
        arch:       'nt'
        tools:      'vs2019'
        owtools:    'VISUALC'
        owdebug:    ${{ vars.OWDEBUG }}
  docsbuild-chm:
    name: Documentation Build CHM
    needs: boot-nt
    runs-on: windows-2019
    timeout-minutes: 90
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/docbuild"
      with:
        target:     'docchm'
        arch:       'nt'
        tools:      'vs2019'
        owtools:    'VISUALC'
        owdebug:    ${{ vars.OWDEBUG }}
  docsbuild-nt:
    name: Documentation Build NT
    needs: boot-nt
    runs-on: windows-2019
    timeout-minutes: 90
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/docbuild"
      with:
        target:     'docnt'
        arch:       'nt'
        tools:      'vs2019'
        owtools:    'VISUALC'
        owdebug:    ${{ vars.OWDEBUG }}
  docsbuild-os2:
    name: Documentation Build OS2
    needs: boot-nt
    runs-on: windows-2019
    timeout-minutes: 90
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/docbuild"
      with:
        target:     'docos2'
        arch:       'nt'
        tools:      'vs2019'
        owtools:    'VISUALC'
        owdebug:    ${{ vars.OWDEBUG }}
  docsbuild-pdf:
    name: Documentation Build PDF
    needs: boot-nt
    runs-on: windows-2019
    timeout-minutes: 90
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/docbuild"
      with:
        target:     'docpdf'
        arch:       'nt'
        tools:      'vs2019'
        owtools:    'VISUALC'
        owdebug:    ${{ vars.OWDEBUG }}
  docsbuild-win:
    name: Documentation Build WIN
    needs: boot-nt
    runs-on: windows-2019
    timeout-minutes: 90
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/docbuild"
      with:
        target:     'docwin'
        arch:       'nt'
        tools:      'vs2019'
        owtools:    'VISUALC'
        owdebug:    ${{ vars.OWDEBUG }}
  docsbuild:
    name: Consolidate Documentation
    needs:
    - docsbuild-dos
    - docsbuild-chm
    - docsbuild-nt
    - docsbuild-os2
    - docsbuild-pdf
    - docsbuild-win
    runs-on: windows-2019
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - uses: "./.github/actions/artfload"
      with:
        arch:       'nt'
        gitpath:    'rel'
        artifact:   'rel docdos'
    - uses: "./.github/actions/artfload"
      with:
        arch:       'nt'
        gitpath:    'rel'
        artifact:   'rel docchm'
    - uses: "./.github/actions/artfload"
      with:
        arch:       'nt'
        gitpath:    'rel'
        artifact:   'rel docnt'
    - uses: "./.github/actions/artfload"
      with:
        arch:       'nt'
        gitpath:    'rel'
        artifact:   'rel docos2'
    - uses: "./.github/actions/artfload"
      with:
        arch:       'nt'
        gitpath:    'rel'
        artifact:   'rel docpdf'
    - uses: "./.github/actions/artfload"
      with:
        arch:       'nt'
        gitpath:    'rel'
        artifact:   'rel docwin'
    - uses: "./.github/actions/artfsave"
      with:
        arch:       'nt'
        gitpath:    'rel'
        artifact:   'rel docsall'
  tests-lnx-gcc:
    name: Tests Linux GCC
    needs: build-lnx-gcc
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Tests Linux GCC
      uses: "./.github/actions/tests"
      with:
        arch:    'lnx'
        pscript: 'ci/buildx.sh'
        tools:   'gcc'
  tests-nt:
    name: Tests Windows
    needs: build-nt
    runs-on: windows-2019
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Tests Windows
      uses: "./.github/actions/tests"
      with:
        arch:    'nt'
        pscript: 'ci/buildx.cmd'
  install-lnx:
    name: Installers Build Linux
    runs-on: ubuntu-20.04
    needs:
    - tests-lnx-gcc
    - tests-nt
    - docsbuild
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Installers Build Linux
      uses: "./.github/actions/install"
      with:
        arch:    'lnx'
        tools:   'gcc'
        pscript: 'ci/buildx.sh'
        owdebug: ${{ vars.OWDEBUG }}
  release-lnx:
    name: "GitHub Release"
    runs-on: ubuntu-20.04
    needs: install-lnx
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: GitHub Release
      uses: "./.github/actions/release"
      with:
        arch:    'lnx'
        tools:   'gcc'
        owdebug: ${{ vars.OWDEBUG }}
