# Build Wiki Documentation
#
# set secret OWGHTOKEN - https 'user name:password'

name: WikiDocs

on:
  push:
    paths:
      - '.github/workflows/wikidocs.yml'
      - '.github/actions/artfdelc/action.yml'
      - '.github/actions/artfload/action.yml'
      - '.github/actions/artfsave/action.yml'
      - '.github/actions/boot/action.yml'
      - '.github/actions/dosboxin/action.yml'
      - '.github/actions/docbuild/action.yml'
      - '.github/actions/curlcmd/action.yml'
      - '.github/actions/tarload/action.yml'
      - '.github/actions/tarsave/action.yml'
      - 'docs/**'
      - 'bld/cc/gml/**'
      - 'bld/cg/doc/**'
      - 'bld/dwarf/dw/doc/**'
      - 'bld/f77/wfc/gml/**'
      - 'bld/plusplus/gml/**'
      - 'bld/wpi/doc/**'
      - 'bld/wv/doc/**'
  workflow_dispatch:

jobs:
  start-start:
    if: github.repository == 'open-watcom/open-watcom-v2' && github.ref == 'refs/heads/master'
    name: Start
    runs-on: ubuntu-latest
    steps:
    - run: echo ""
      shell: bash
  boot:
    needs: start-start
    if: github.ref == 'refs/heads/master'
    name: Bootstrap
    runs-on: windows-2019
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Bootstrap
      uses: "./.github/actions/boot"
      with:
        arch:       'nt'
        bldscript:  'ci\buildx.cmd'
        tools:      'vs2019'
        owtools:    'VISUALC'
        owdebug:    ${{ vars.OWDEBUG }}
  wiki-build:
    needs: boot
    name: Wiki build
    runs-on: windows-2019
    strategy:
      matrix:
        include:
        - display: 'HTML'
          doctype: 'wikihtml'
        - display: 'PDF'
          doctype: 'wikipdf'
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Docs Build
      uses: "./.github/actions/docbuild"
      with:
        target:     ${{ matrix.doctype }}
        arch:       'nt'
        tools:      'vs2019'
        owtools:    'VISUALC'
        owdebug:    ${{ vars.OWDEBUG }}
  wiki-update:
    name: Wiki Documentation Update
    needs: wiki-build
    runs-on: windows-2019
    steps:
    - name: Setup Git User
      shell: cmd
      run: |
        git config --global user.email "openwatcom.github@gmail.com"
        git config --global user.name "Open Watcom GitHub"
    - name: Wiki Repo clone
      shell: cmd
      run: |
        git clone -v --depth=1 --branch=master https://%OWGHTOKEN%@github.com/%OWWIKIPROJ%.git .
      env:
        OWGHTOKEN: ${{ secrets.OWGHTOKEN }}
        OWWIKIPROJ: open-watcom/open-watcom-v2-wikidocs
    - uses: "./.github/actions/artfload"
      with:
        arch:     'nt'
        gitpath:  'docs'
        artifact: 'rel wikihtml'
        tools:    'vs2019'
        owdebug:  ${{ vars.OWDEBUG }}
    - uses: "./.github/actions/artfload"
      with:
        arch:     'nt'
        gitpath:  'docs'
        artifact: 'rel wikipdf'
        tools:    'vs2019'
        owdebug:  ${{ vars.OWDEBUG }}
    - name: Wiki Repo Update
      shell: cmd
      run: |
        git add -v -f .
        git commit -v -m "GitHub Workflow build"
        git push -v
  cleanup:
    needs: wiki-update
    name: Call to delete Artifacts
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.5.0
    - name: Call to delete Artifacts
      uses: "./.github/actions/artfdelc"
      with:
        owdebug:    ${{ vars.OWDEBUG }}
